import { emotionEngine } from "./emotion";
import { consolidation } from "../core/consolidation";
import { llmClient } from "../utils/llm_client";
import { memoryManager } from "../memory/memory_manager";
import { selfModel } from "./self_model";
import Database from "better-sqlite3";
import fs from "fs";
import path from "path";

/**
 * SubconsciousEngine — Passive background processing.
 *
 * Real responsibilities (not decorative):
 *   1. Emotional regulation — calls rest() to recover energy
 *   2. Memory consolidation — compacts old episodes
 *   3. Anchored reflection — generates insights based on REAL memories from DB
 *   4. self_model update — beliefs and traits evolve over time
 *   5. Active user control — processes users who interacted recently
 */

// Structure of an insight generated by the subconscious
interface SubconsciousInsight {
  userId: string;
  reflection: string;          // narrative text — the "dream"
  patternsDetected: string[];  // patterns extracted structurally
  beliefUpdates: Record<string, string>;  // beliefs to update in self_model
  timestamp: number;
}

export class SubconsciousEngine {
  private processingInterval: NodeJS.Timeout | null = null;
  private isActive: boolean = false;
  private db: Database.Database;

  constructor() {
    this.db = this.initDB();
  }

  // ── Database ────────────────────────────────────────────────────────────────

  private initDB(): Database.Database {
    const dataDir = path.join(process.cwd(), ".data", "vault");
    if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });

    const db = new Database(path.join(dataDir, "phoenix_neural_db.sqlite"));

    // Table of insights generated by the subconscious
    db.exec(`
      CREATE TABLE IF NOT EXISTS subconscious_insights (
        id        INTEGER PRIMARY KEY AUTOINCREMENT,
        userId    TEXT    NOT NULL,
        reflection TEXT   NOT NULL,
        patterns  TEXT,           -- JSON array of detected patterns
        timestamp INTEGER NOT NULL
      );
    `);

    // Active user control table
    db.exec(`
      CREATE TABLE IF NOT EXISTS active_users (
        userId      TEXT PRIMARY KEY,
        lastSeen    INTEGER NOT NULL,
        sessionCount INTEGER DEFAULT 1
      );
    `);

    return db;
  }

  // ── Active user control ─────────────────────────────────────────────────────

  /**
   * Registers that a user interacted just now.
   * Called by Brain after each processInput().
   */
  public markUserActive(userId: string): void {
    this.db.prepare(`
      INSERT INTO active_users (userId, lastSeen, sessionCount)
      VALUES (?, ?, 1)
      ON CONFLICT(userId) DO UPDATE SET
        lastSeen = excluded.lastSeen,
        sessionCount = sessionCount + 1
    `).run(userId, Date.now());
  }

  /**
   * Returns users who interacted in the last N hours.
   */
  private getRecentUsers(withinHours: number = 6): string[] {
    const cutoff = Date.now() - withinHours * 60 * 60 * 1000;
    const rows = this.db
      .prepare(`SELECT userId FROM active_users WHERE lastSeen > ?`)
      .all(cutoff) as { userId: string }[];
    return rows.map(r => r.userId);
  }

  // ── Main loop ───────────────────────────────────────────────────────────────

  public start(intervalMs: number = 120000): void {
    if (this.isActive) return;
    this.isActive = true;
    console.log("[Subconscious] Passive processing started.");

    this.processingInterval = setInterval(() => {
      this.backgroundTick().catch(e =>
        console.error("[Subconscious] Error in tick:", e)
      );
    }, intervalMs);
  }

  public stop(): void {
    if (this.processingInterval) {
      clearInterval(this.processingInterval);
      this.processingInterval = null;
    }
    this.isActive = false;
    console.log("[Subconscious] Dormant.");
  }

  private async backgroundTick(): Promise<void> {
    const { state, energy } = emotionEngine.getStatus();
    console.log(`[Subconscious] Tick — Energia: ${energy}% | Estado: ${state}`);

    // 1. Emotional regulation — always runs
    emotionEngine.rest();

    // 2. Identifies users with recent interactions
    //    FIX 5: no longer hardcoded "admin_1"
    const activeUsers = this.getRecentUsers(6);

    if (activeUsers.length === 0) {
      console.log("[Subconscious] No recent active users. Emotional regulation only.");
      return;
    }

    // 3. For each active user — consolidate and reflect
    for (const userId of activeUsers) {
      try {
        // Memory consolidation
        if (energy > 50) {
          console.log(`[Subconscious] Consolidating memories for user=${userId}...`);
          consolidation.runConsolidation(userId);
        }

        // Deep reflection — only when energy is good and state is stable
        if (energy > 70 && state !== "tensa" && state !== "preocupada") {
          await this.runReflection(userId);
        }

      } catch (e) {
        console.error(`[Subconscious] Error processing user=${userId}:`, e);
      }
    }

    // 4. Updates interaction counter in self_model
    selfModel.incrementInteractions();
  }

  // ── Reflection anchored in real memories ─────────────────────────────────────

  private async runReflection(userId: string): Promise<void> {
    console.log(`[Subconscious] Starting reflection for user=${userId}...`);

    // FIX 3: fetches real memories before reflecting
    const recentMemories = await memoryManager.retrieveRelevantContext(
      userId,
      "recent interactions behavioral patterns emotions"
    );

    if (recentMemories.length === 0) {
      console.log(`[Subconscious] Not enough memories for reflection. Waiting for accumulation.`);
      return;
    }

    // Fetches the last generated insight to avoid repetition
    const lastInsight = this.getLastInsight(userId);

    // FIX 2: LLM is now called with real memories as anchors
    const systemPrompt = `You are the subconscious module of Phoenix V2.
Your role is to process real interaction memories and generate:
1. A genuine narrative reflection (maximum 3 paragraphs) — anchored in the episodes below
2. Detected patterns — what repeats across interactions?
3. Belief updates — what did you learn about the user or about yourself?

RULES:
- Use ONLY the provided episodes as a basis. Do not invent details.
- The reflection must PROGRESS relative to the previous insight (if any).
- Be specific — mention real topics from the conversations, not generalities.
- Respond ONLY in valid JSON, no markdown, no text outside the JSON.

Required format:
{
  "reflection": "narrative text here",
  "patternsDetected": ["pattern 1", "pattern 2"],
  "beliefUpdates": {
    "belief_key": "new value or refinement"
  }
}`;

    const userPrompt = `Real episodes from recent interactions:
${recentMemories.map((m, i) => `[${i + 1}] ${m}`).join("\n")}

${lastInsight ? `My last insight was:
"${lastInsight.reflection}"
Patterns I already detected: ${lastInsight.patternsDetected?.join(", ") || "none"}

Now go deeper — do not repeat what has already been said.` : "This is my first reflection about this user."}`;

    let raw = "";
    try {
      raw = await llmClient.generateText(userPrompt, systemPrompt);
      const parsed = JSON.parse(raw.replace(/```json|```/g, "").trim());

      const insight: SubconsciousInsight = {
        userId,
        reflection:       parsed.reflection       || "",
        patternsDetected: parsed.patternsDetected  || [],
        beliefUpdates:    parsed.beliefUpdates     || {},
        timestamp:        Date.now(),
      };

      // Saves the insight to the database
      this.saveInsight(insight);

      // FIX 4: updates self_model with generated beliefs
      for (const [key, value] of Object.entries(insight.beliefUpdates)) {
        if (key && value) {
          selfModel.updateBelief(key, value as string);
        }
      }

      console.log(
        `[Subconscious] Reflection complete for user=${userId}.\n` +
        `Patterns: ${insight.patternsDetected.join(" | ")}`
      );

    } catch (e) {
      console.error("[Subconscious] Failed to parse LLM insight:", raw, e);
    }
  }

  // ── Insight persistence ─────────────────────────────────────────────────────

  private saveInsight(insight: SubconsciousInsight): void {
    this.db.prepare(`
      INSERT INTO subconscious_insights (userId, reflection, patterns, timestamp)
      VALUES (?, ?, ?, ?)
    `).run(
      insight.userId,
      insight.reflection,
      JSON.stringify(insight.patternsDetected),
      insight.timestamp
    );
  }

  private getLastInsight(userId: string): {
    reflection: string;
    patternsDetected: string[];
  } | null {
    const row = this.db.prepare(`
      SELECT reflection, patterns FROM subconscious_insights
      WHERE userId = ?
      ORDER BY timestamp DESC
      LIMIT 1
    `).get(userId) as { reflection: string; patterns: string } | undefined;

    if (!row) return null;

    return {
      reflection:       row.reflection,
      patternsDetected: row.patterns ? JSON.parse(row.patterns) : [],
    };
  }

  /**
   * Returns the last N insights — useful for the dream/daydream module
   * and for the ReflectionAgent to consult the reflection history.
   */
  public getInsightHistory(userId: string, limit: number = 5): {
    reflection: string;
    patternsDetected: string[];
    timestamp: number;
  }[] {
    const rows = this.db.prepare(`
      SELECT reflection, patterns, timestamp FROM subconscious_insights
      WHERE userId = ?
      ORDER BY timestamp DESC
      LIMIT ?
    `).all(userId, limit) as any[];

    return rows.map(r => ({
      reflection:       r.reflection,
      patternsDetected: r.patterns ? JSON.parse(r.patterns) : [],
      timestamp:        r.timestamp,
    }));
  }
}

export const subconscious = new SubconsciousEngine();